import type { Metadata } from "next";
import "./globals.scss";
import MainProvider from "../providers/MainProvider";

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ru" }];
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang}>
      <body id="__next">
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
